spring.application.name=Cosmo Cats Marketplace

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

currency-api.base-url=https://api.frankfurter.dev/v1

feature.cosmoCats.enabled=true
feature.kittyProducts.enabled=false
