spring.application.name=Cosmo Cats Marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/cosmocats
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=cosmocats
spring.datasource.password=cosmocats
spring.jpa.hibernate.ddl-auto=none

currency-api.base-url=https://api.frankfurter.dev/v1

feature.cosmoCats.enabled=true
feature.kittyProducts.enabled=false
